#-----------------------------R Code To Modify in the Classroom Lecture with Students-----------------------
#-----------------------------R API List for References in the TeX Language for Lectures -------------------------------------------------------------------
#-----------------------------------------------Differential Equations---------------------------------------------------------
library(deSolve)
library(ReacTran)
library(rootSolve)
library(fda)
library(phaseR)
#-----------------------------------------------Probability Theory--------------------------------------------------------------
library(boot)
library(sampling)
library(PearsonDS)
library(fitdistrplus)
library(GA)
#-----------------------------------------------Wavelet Theory-----------------------------------------------------------------
library(wmtsa)
library(wavelets)
library(wavethresh)
library(waveslim)
library(wavemulcor)
library(FGN)
library(tseriesChaos)
#-----------------------------------------------Tables and Figures----------------------------------------------------------------
library(xtable)
library(car)
library(igraph)
library(corrplot)
library(psych)
library(ggplot2)
#-----------------------------------------------References---------------------------------------------------------------------

toBibtex(citation('deSolve'))
toBibtex(citation('ReacTran'))
toBibtex(citation('rootSolve'))
toBibtex(citation('fda'))
toBibtex(citation('xtable'))
toBibtex(citation('boot'))
toBibtex(citation('sampling'))
toBibtex(citation('PearsonDS'))
toBibtex(citation('phaseR'))
toBibtex(citation('GA'))
toBibtex(citation('car'))
toBibtex(citation('igraph'))

toBibtex(citation('wmtsa'))
toBibtex(citation('wavelets'))
toBibtex(citation('wavethresh'))
toBibtex(citation('waveslim'))
toBibtex(citation('wavemulcor'))
toBibtex(citation('fitdistrplus'))

toBibtex(citation('psych'))
toBibtex(citation('FGN'))
toBibtex(citation('tSeriesChaos'))
toBibtex(citation('corrplot'))
toBibtex(citation('ggplot2'))
